import os
import sys
from faster_whisper import WhisperModel

TOKEN_FILE = os.path.join(os.path.dirname(__file__), "../.env")

if os.path.exists(TOKEN_FILE):
  with open(TOKEN_FILE, "r") as f:
    os.environ["HF_TOKEN"] = f.read().strip()
else:
  print("⚠️ Warning: token.txt not found. Running with unauthenticated limits.", file=sys.stderr)

class VendingTranscriber:
  # Changed default to 'base' so it aligns with your updated detect.py
  def __init__(self, model_size="small", device="cpu"):
    """
    Initializes the optimized local transcription model.
    Model sizes: 'tiny', 'base', 'small', 'tiny' is perfect for high-speed kiosks.
    Device: Set to 'cuda' if you are running on a dedicated NVIDIA GPU later.
    """
    print(f"📦 Loading local Whisper STT Engine ({model_size} model on {device})...")
    # beam_size=1 and compute_type="int8" ensure the fastest possible conversion turnaround
    self.model = WhisperModel(model_size, device=device, compute_type="int8")
    print("🚀 Whisper STT Engine loaded and ready.")

  def transcribe_audio(self, wav_file_path):
    """Turns a physical WAV file into a clean string text transcription"""
    if not os.path.exists(wav_file_path):
      print(f"⚠️ Error: Audio file {wav_file_path} not found.")
      return ""
    
    try:
      # VENDING MACHINE CONTEXT PRIMING
      # This hint gives Whisper a "cheat sheet" of the vocabulary it should expect to hear.
      vending_hint = "Ciao! Vorrei uno snack, da bere, acqua, ho fame. Hello, looking for a drink or sweet."

      # Run local voice-to-text inference
      # Switched language to "it" to match your Italian UI and AI text. 
      # (If you want it to auto-detect the language instead, remove the language="it" argument entirely).
      segments, info = self.model.transcribe(
          wav_file_path, 
          beam_size=1, 
          language="it", 
          initial_prompt=vending_hint
      )

      # Combine individual spoken word segments into a unified sentence string
      full_text = ""
      for segment in segments:
        full_text += segment.text + " "

      return full_text.strip()
    
    except Exception as e:
      print(f"❌ Transcription internal error: {e}", file=sys.stderr)
      return ""
    
# Standalone execution diagnostic test block
if __name__ == "__main__":
  # Target the test file generated by the audio_recorder.py module
  test_file = "customer_input.wav"

  if not os.path.exists(test_file):
    print(f"❌ Missing target file: {test_file}. Please run audio_recorder.py first to generate a sample!")
  else:
    transcriber = VendingTranscriber(model_size="base", device="cpu")
    print("\n📝 Decoding audio file baseline...")
    result_text = transcriber.transcribe_audio(test_file)
    print("\n🎯 Transcription Output result:")
    print(f'"{result_text}"')